[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = [
  "pnpm install",
]

[phases.build]
cmds = [
  "cd /app/frontend && pnpm run build",
  "cd /app/backend && pnpm run build"
]

[start]
cmd = "cd /app/frontend && pnpm start & cd /app/backend && pnpm start"