[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = [
  "ls",
]

[phases.build]
cmds = [
  "cd frontend && pnpm run build",
  "cd backend && pnpm run build"
]

[start]
cmd = "cd frontend && pnpm start & cd backend && pnpm start"